(()=>{
  const lang=document.documentElement.lang||'fr';
  const messages={
    fr:{sending:'Envoi en cours…',contactOk:'Votre proposition a bien été envoyée.',applicationOk:'Votre candidature a bien été envoyée.',error:'Envoi impossible. Merci de réessayer.',fileType:'Le CV doit être au format PDF, DOC ou DOCX.',fileSize:'Le CV ne doit pas dépasser 2,5 Mo.',fileRead:'Le CV n’a pas pu être lu.'},
    en:{sending:'Sending…',contactOk:'Your proposal has been sent.',applicationOk:'Your application has been sent.',error:'Unable to send. Please try again.',fileType:'The CV must be a PDF, DOC or DOCX file.',fileSize:'The CV must not exceed 2.5 MB.',fileRead:'The CV could not be read.'},
    es:{sending:'Enviando…',contactOk:'Su propuesta ha sido enviada.',applicationOk:'Su candidatura ha sido enviada.',error:'No se ha podido enviar. Inténtelo de nuevo.',fileType:'El CV debe estar en formato PDF, DOC o DOCX.',fileSize:'El CV no debe superar 2,5 MB.',fileRead:'No se ha podido leer el CV.'},
    nl:{sending:'Verzenden…',contactOk:'Uw voorstel is verzonden.',applicationOk:'Uw sollicitatie is verzonden.',error:'Verzenden mislukt. Probeer opnieuw.',fileType:'Het CV moet een PDF-, DOC- of DOCX-bestand zijn.',fileSize:'Het CV mag niet groter zijn dan 2,5 MB.',fileRead:'Het CV kon niet worden gelezen.'},
    de:{sending:'Wird gesendet…',contactOk:'Ihr Vorschlag wurde gesendet.',applicationOk:'Ihre Bewerbung wurde gesendet.',error:'Senden nicht möglich. Bitte erneut versuchen.',fileType:'Der Lebenslauf muss als PDF, DOC oder DOCX vorliegen.',fileSize:'Der Lebenslauf darf höchstens 2,5 MB groß sein.',fileRead:'Der Lebenslauf konnte nicht gelesen werden.'}
  }[lang]||null;
  const msg=messages||{sending:'Envoi en cours…',contactOk:'Votre proposition a bien été envoyée.',applicationOk:'Votre candidature a bien été envoyée.',error:'Envoi impossible. Merci de réessayer.',fileType:'Le CV doit être au format PDF, DOC ou DOCX.',fileSize:'Le CV ne doit pas dépasser 2,5 Mo.',fileRead:'Le CV n’a pas pu être lu.'};
  const setStatus=(form,text,state='')=>{const status=form.querySelector('[data-form-status]');if(status){status.textContent=text;status.className=`cp-status ${state}`.trim()}};
  const send=async(form,url,body,success,conversion)=>{const button=form.querySelector('button[type="submit"]');button.disabled=true;setStatus(form,msg.sending);try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||msg.error);setStatus(form,success,'success');window.va?.('pageview',{route:conversion,path:conversion});form.reset()}catch(error){setStatus(form,error.message||msg.error,'error')}finally{button.disabled=false}};
  document.querySelectorAll('[data-contact-form]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const body=Object.fromEntries(new FormData(form));body.consent=Boolean(form.elements.consent?.checked);send(form,'/api/contact',body,msg.contactOk,'/conversion/partenariat-envoye')}));
  const toBase64=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error(msg.fileRead));reader.readAsDataURL(file)});
  document.querySelectorAll('[data-application-form]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();const file=form.elements.cv?.files?.[0];const extension=(file?.name.split('.').pop()||'').toLowerCase();if(!file||!['pdf','doc','docx'].includes(extension)){setStatus(form,msg.fileType,'error');return}if(file.size>2621440){setStatus(form,msg.fileSize,'error');return}try{const body=Object.fromEntries(new FormData(form));delete body.cv;body.consent=Boolean(form.elements.consent?.checked);body.cv={name:file.name,type:file.type,size:file.size,content:await toBase64(file)};await send(form,'/api/application',body,msg.applicationOk,'/conversion/candidature-envoyee')}catch(error){setStatus(form,error.message||msg.error,'error')}}));
})();
