window.DY_PRODUCTS={
 'cvdesignpro':{name:'CVDesignPro',cat:'emploi-carriere',art:'emploi',img:'cvdesignpro',url:'https://www.cvdesignpro.com/fr',tag:'CV · ATS · recrutement',problem:'Créer un CV lisible, crédible et adapté à une offre sans perdre du temps à reprendre toute la mise en page.',audience:'Candidats, organismes de formation, cabinets d’accompagnement et équipes de recrutement.',value:'Un parcours guidé pour structurer le CV, l’adapter à une candidature, contrôler sa cohérence et préparer les documents associés.',features:['Création et mise en forme du CV','Analyse de compatibilité ATS','Adaptation à une offre d’emploi','Lettre de motivation','Accompagnement multilingue'],uses:['Préparer une première candidature','Repositionner un profil expérimenté','Adapter un CV à une offre précise'],compare:'Par rapport à un éditeur graphique généraliste, la démarche privilégie le contenu de candidature, la lisibilité et les critères de recrutement.'},
 'quizplay':{name:'QuizPlay',cat:'education',art:'education',img:'quizplay',url:'https://quizplay-production.up.railway.app/',tag:'Quiz interactifs',problem:'Maintenir l’attention d’une classe ou d’un groupe et vérifier la compréhension sans alourdir la séance.',audience:'Enseignants, formateurs, animateurs et responsables pédagogiques.',value:'Créer et animer des quiz avec retour immédiat pour transformer l’évaluation en séquence d’apprentissage.',features:['Création rapide de questions','Animation collective','Résultats immédiats','Utilisation en classe ou à distance','Progression pédagogique'],uses:['Évaluation formative','Révision avant examen','Animation de formation'],compare:'Une alternative centrée sur la simplicité et le scénario pédagogique, à étudier selon les besoins face à Kahoot ou Wooclap.'},
 'courshub':{name:'CoursHub',cat:'education',art:'education',img:'courshub',url:'https://coursehub-dusky-seven.vercel.app',tag:'Ressources pédagogiques',problem:'Les cours et supports sont dispersés entre dossiers, messageries et espaces de stockage difficiles à parcourir.',audience:'Enseignants, formateurs, établissements et apprenants.',value:'Centraliser, organiser, retrouver et partager les ressources pédagogiques dans une bibliothèque cohérente.',features:['Création de ressources','Classement thématique','Recherche','Partage de cours','Capitalisation collective'],uses:['Bibliothèque d’établissement','Catalogue de formation','Partage entre enseignants'],compare:'Contrairement à un simple dossier partagé, la plateforme ajoute une structure éditoriale et une navigation pensée pour les contenus pédagogiques.'},
 'ecole-connect':{name:'École Connect',cat:'education',art:'education',img:'ecole-connect',url:'https://ecole-connect-pied.vercel.app',tag:'Communication scolaire',problem:'Messages, devoirs, documents et événements se dispersent entre plusieurs applications, emails et groupes de discussion.',audience:'Établissements, directions, équipes éducatives, élèves et familles.',value:'Un espace configurable pour centraliser la communication et rendre les informations scolaires plus faciles à suivre.',features:['Actualités et messages','Agenda scolaire','Documents partagés','Suivi des informations','Accès selon les profils'],uses:['Communication école-parents','Diffusion de documents','Organisation d’événements'],compare:'La plateforme vise à réduire la fragmentation plutôt qu’à ajouter une application de plus au parcours des familles.'},
 'firmoscope':{name:'Firmoscope',cat:'annuaire',art:'entreprises',img:'firmoscope',url:'https://prospeo-drab.vercel.app',tag:'Annuaire B2B',problem:'Trouver une entreprise pertinente et comprendre son contexte exige souvent de croiser plusieurs sources.',audience:'Commerciaux, dirigeants, consultants et équipes de développement économique.',value:'Rendre l’information professionnelle recherchable, filtrable et directement exploitable.',features:['Recherche d’entreprises','Filtres professionnels','Fiches contextualisées','Opportunités B2B','Sources identifiables'],uses:['Prospection ciblée','Cartographie d’un marché','Recherche de partenaires'],compare:'Face à des annuaires comme Pappers, la valeur recherchée porte sur les parcours d’exploration et la mise en action des informations.'},
 'arbitrage-plus':{name:'Arbitrage+',cat:'commerce',art:'arbitrage',img:'arbitrage-plus',url:'https://arbitrage-pro-app.vercel.app',tag:'Comparaison de prix',problem:'Un écart de prix apparent ne suffit pas à prouver qu’une opportunité commerciale est rentable.',audience:'Vendeurs en ligne, acheteurs, analystes et entrepreneurs.',value:'Comparer les prix et intégrer les principaux coûts pour qualifier une opportunité avant d’acheter.',features:['Comparaison de prix','Calcul de marge','Prise en compte des frais','Qualification des opportunités','Historique d’analyse'],uses:['Arbitrage en ligne','Sélection de produits','Préparation d’un achat'],compare:'L’analyse peut compléter des données issues de plateformes comme Keepa ou des outils de sourcing comme SellerAmp, sans prétendre les remplacer sur tous leurs usages.'},
 'analyzer-plus':{name:'Analyzer+',cat:'commerce',art:'arbitrage',img:'analyzer-plus',url:'https://analyzer-plus-preview.vercel.app',tag:'Analyse produit',problem:'Décider à partir d’un seul prix ou d’un score opaque masque les coûts, la concurrence et les incertitudes.',audience:'Vendeurs marketplace, responsables e-commerce et analystes produits.',value:'Rassembler les critères utiles pour comparer plusieurs produits avec une méthode explicable.',features:['Fiche d’analyse','Coûts et concurrence','Critères comparables','Hypothèses visibles','Aide à la décision'],uses:['Étude avant référencement','Comparaison de produits','Revue de portefeuille'],compare:'L’outil structure une décision interne ; les données historiques spécialisées de services comme Keepa peuvent rester complémentaires.'},
 'profit-plus':{name:'Profit+',cat:'commerce',art:'ecommerce',img:'profit-plus',url:'https://profit-plus-preview.vercel.app',tag:'Rentabilité e-commerce',problem:'Le chiffre d’affaires ne révèle ni la marge réelle ni les produits dont les coûts dérivent.',audience:'Vendeurs e-commerce, entrepreneurs marketplace et responsables de portefeuille.',value:'Suivre ventes, dépenses, marges et écarts par rapport aux hypothèses initiales.',features:['Tableau de bord','Suivi des dépenses','Calcul de marge','Analyse par produit','Alertes de dérive'],uses:['Pilotage mensuel','Analyse de rentabilité','Arbitrage de portefeuille'],compare:'Une vue dédiée à la rentabilité opérationnelle, complémentaire des tableaux fournis par les places de marché.'},
 'erpbridge':{name:'Solutions de gestion connectée',cat:'gestion',art:'automatisation',img:'erpbridge',url:'/contact',tag:'Gestion · automatisation',problem:'Les doubles saisies et les outils isolés ralentissent les équipes et fragilisent la qualité des données.',audience:'PME, associations, organismes de formation et équipes opérationnelles.',value:'Cartographier le processus, connecter les outils et automatiser uniquement les étapes qui apportent un gain mesurable.',features:['Audit des processus','Connecteurs API','Automatisations','Workflows métiers','Accompagnement des équipes'],uses:['Synchronisation CRM-facturation','Circuit de validation','Reporting automatisé'],compare:'Selon le contexte, une intégration autour d’Odoo peut être pertinente ; une solution plus ciblée convient mieux lorsque le besoin porte sur quelques workflows précis.'},
 'marketplace':{name:'Marketplace personnalisable',cat:'marketplaces',art:'marque-blanche',img:'marketplace',url:'/contact',tag:'Marketplace · marque blanche',problem:'Construire une marketplace complète exige des profils, annonces, recherche, paiements, règles de transaction et administration.',audience:'Entrepreneurs, fédérations, réseaux professionnels et entreprises verticales.',value:'Partir d’un socle personnalisable pour valider un modèle puis adapter l’expérience, les transactions et la marque.',features:['Profils et annonces','Recherche et filtres','Parcours de transaction','Administration','Personnalisation de marque'],uses:['Marketplace de services','Portail B2B','Plateforme de location'],compare:'Sharetribe fournit un moteur no-code et headless complet ; un socle Dyonysos est à envisager lorsque le contrôle du produit, du déploiement ou des workflows spécifiques est prioritaire.'},
 'creation-graphique':{name:'Création graphique',cat:'graphisme',art:'graphisme',img:'creation-graphique',url:'/espace-prive',tag:'Création · adaptation',problem:'Décliner rapidement un contenu dans plusieurs formats sans perdre la cohérence visuelle.',audience:'Équipes marketing, créateurs et petites organisations.',value:'Créer, redimensionner et adapter des contenus visuels dans un parcours simplifié.',features:['Formats multicanaux','Modèles réutilisables','Adaptation des dimensions','Bibliothèque de ressources','Export'],uses:['Publications sociales','Supports commerciaux','Visuels de campagne'],compare:'Canva propose une suite très large ; cette approche vise des workflows ciblés et personnalisables pour une organisation.'},
 'applications-mobiles':{name:'Applications mobiles',cat:'applications',art:'saas',img:'apps-mobiles',url:'/applications',tag:'Mobile · prototypes',problem:'Un projet mobile devient coûteux lorsqu’il démarre par trop de fonctions sans valider l’usage principal.',audience:'Entreprises, entrepreneurs et organisations ayant un usage mobile précis.',value:'Prototyper le parcours essentiel, tester la valeur et développer progressivement.',features:['Cadrage du besoin','Prototype interactif','Design mobile','Développement progressif','Mesure des usages'],uses:['Outil métier terrain','Service grand public','Extension mobile d’une plateforme'],compare:'La priorité est donnée à l’usage et à la validation avant la multiplication des fonctionnalités.'},
 'formation-conseil':{name:'Formation & Conseil',cat:'formation-conseil',art:'education',img:'formation-conseil',url:'/formation-conseil',tag:'Formation · gestion de projet · conseil',problem:'Une formation générique produit peu d’effet lorsqu’elle ne correspond ni au niveau des participants, ni aux outils, ni aux projets réels de l’organisation.',audience:'Entreprises, organismes de formation, universités, écoles, managers, chefs de projet et équipes opérationnelles.',value:'Construire un parcours directement applicable, associant méthode, exercices contextualisés, transfert de compétences et accompagnement.',features:['Microsoft Project','Gestion de projet','PM² et bonnes pratiques PMP','Business analysis','Conseil sur mesure'],uses:['Formation intra-entreprise','Intervention universitaire','Accompagnement d’un chef de projet'],compare:'Le bon format dépend du résultat attendu : prise en main d’un outil, professionnalisation, résolution d’un problème projet ou transformation plus large.'}
};
window.DY_ARTICLES=[
 ['optimiser-cv-ats','cvdesignpro','Comment optimiser un CV pour les ATS ?','optimisation CV ATS, CV compatible ATS'],['adapter-cv-offre-emploi','cvdesignpro','Comment adapter son CV à une offre d’emploi ?','adapter CV offre emploi, candidature ciblée'],['outils-ia-ameliorer-cv','cvdesignpro','Quels outils IA utiliser pour améliorer son CV ?','outil IA CV, améliorer CV'],['cvdesignpro-vs-outils-cv','cvdesignpro','CVDesignPro ou outil de création de CV : que choisir ?','CVDesignPro comparatif, outil création CV'],['comment-recruteurs-analysent-cv','cvdesignpro','Comment les recruteurs analysent-ils un CV ?','analyse CV recruteur, critères recrutement'],
 ['digitaliser-communication-ecole-parents','ecole-connect','Comment digitaliser la communication école-parents ?','communication école parents, application scolaire'],['plateforme-numerique-ecole','ecole-connect','Quelle plateforme numérique choisir pour une école ?','plateforme numérique école, logiciel scolaire'],['centraliser-devoirs-notes-agenda','ecole-connect','Centraliser devoirs, agenda et communication scolaire','centraliser vie scolaire, agenda école'],['alternative-applications-scolaires','ecole-connect','Une alternative à la multiplication des applications scolaires','alternative application scolaire, portail école'],
 ['creer-quiz-interactif-classe','quizplay','Comment créer un quiz interactif pour une classe ?','quiz interactif classe, quiz enseignant'],['alternative-kahoot-wooclap','quizplay','QuizPlay, Kahoot ou Wooclap : comment choisir ?','alternative Kahoot, alternative Wooclap'],['rendre-formation-interactive','quizplay','Comment rendre une formation plus interactive ?','formation interactive, engagement apprenants'],
 ['creer-partager-cours-en-ligne','courshub','Comment créer et partager des cours en ligne ?','partager cours en ligne, créer ressources pédagogiques'],['plateforme-ressources-pedagogiques','courshub','Choisir une plateforme de ressources pédagogiques','plateforme ressources pédagogiques, outils enseignants'],
 ['annuaire-entreprises-prospection-b2b','firmoscope','Comment utiliser un annuaire d’entreprises pour la prospection B2B ?','annuaire entreprises B2B, prospection entreprises'],['firmoscope-alternative-pappers','firmoscope','Firmoscope et Pappers : des usages complémentaires','alternative Pappers, recherche entreprise'],
 ['calculer-rentabilite-arbitrage','arbitrage-plus','Comment calculer la rentabilité d’une opportunité d’arbitrage ?','calcul rentabilité arbitrage, marge e-commerce'],['alternative-selleramp','arbitrage-plus','Arbitrage+ et SellerAmp : quels critères comparer ?','alternative SellerAmp, outil arbitrage Amazon'],
 ['analyser-produit-avant-achat','analyzer-plus','Comment analyser un produit avant de l’acheter ?','analyse produit e-commerce, décision achat'],['keepa-analyse-produit','analyzer-plus','Keepa et outils d’analyse produit : comment les combiner ?','Keepa analyse produit, alternative Keepa'],
 ['suivre-marge-ecommerce','profit-plus','Comment suivre sa marge réelle en e-commerce ?','suivi marge e-commerce, tableau rentabilité'],['tableau-bord-profit-amazon','profit-plus','Construire un tableau de bord de profit marketplace','profit Amazon, tableau de bord vendeur'],
 ['automatiser-processus-pme','erpbridge','Comment automatiser les processus d’une PME sans complexité ?','automatisation PME, workflow métier'],['odoo-ou-solution-ciblee','erpbridge','Odoo ou solution métier ciblée : comment choisir ?','alternative Odoo, Odoo comparatif'],
 ['creer-marketplace','marketplace','Comment créer une marketplace de services ou de produits ?','créer marketplace, plateforme multi-vendeurs'],['alternative-sharetribe','marketplace','Alternative à Sharetribe : quels critères de choix ?','alternative Sharetribe, logiciel marketplace'],
 ['alternative-canva-entreprise','creation-graphique','Canva ou outil de création adapté à l’entreprise ?','alternative Canva, outil création entreprise'],['adapter-contenus-multicanaux','creation-graphique','Comment adapter un contenu à plusieurs canaux ?','adapter contenu réseaux sociaux, formats visuels'],
 ['reussir-prototype-application-mobile','applications-mobiles','Comment réussir un prototype d’application mobile ?','prototype application mobile, MVP mobile'],['application-mobile-sur-mesure','applications-mobiles','Application mobile sur mesure ou solution SaaS ?','application mobile sur mesure, SaaS mobile'],
 ['formation-ms-project-entreprise','formation-conseil','Formation MS Project en entreprise : programme et bénéfices','formation MS Project entreprise, cours Microsoft Project'],
 ['formation-gestion-projet-organisme','formation-conseil','Comment construire une formation en gestion de projet efficace ?','formation gestion de projet, organisme de formation'],
 ['formateur-gestion-projet-universite-ecole','formation-conseil','Faire intervenir un formateur en gestion de projet dans une université ou une école','formateur gestion de projet université, intervenant école'],
 ['conseil-gestion-projet-sur-mesure','formation-conseil','Quand faire appel à un consultant en gestion de projet ?','conseil gestion de projet, consultant PMO']
];
